version: '3'
services:
  web:
    environment:
      - REACT_APP_GRAPHQL_URL=http://api/graphql
    build: ./client
    ports:
      - "3000:80"
  api:
    build: ./graphql-gateway
    ports:
      - "3001:3001"
